### ISSUE TITLE
Add set_api_key() without argument to look for the file ~/.freddatarc if the API_FRED environment variable doesn't exist.

### ISSUE THREAD

**Issue by proudindiv** [markushhh/FredApi.jl#7]
The alternate FredData.jl package looks for the ~/.freddatarc file if no key argument is given and its FRED_API_KEY environment variable isn't set:

https://github.com/micahjsmith/FredData.jl/blob/master/src/FredData.jl :
```
Constructors
------------
- `Fred()`: Key detected automatically. First, looks for the environment variable
    FRED_API_KEY, then looks for the file ~/.freddatarc.
- `Fred(key::AbstractString)`: User specifies key directly
```
This makes it easier to hide the key when using jupyter noteboooks or releasing code to the public.

Thanks,
Gary

**Comment by markushhh** [comment]
You do not need to call `set_api_key` in the scripts, iff you've set the API key in the environment variables. 

I discourage the use of `set_api_key`. The function is solely implemented to have a look at the package or in case you want to download data once, and not clutter your environment variables.

`get_symbols` looks for `ENV["API_FRED"]`. If the key is specified with `set_api_key` it overrides the environment variable locally. Adding the `.freddatarc` file to the home directory is possible but introduces ambiguity. Which key should be the default?

IMO `set_api_key()` without arguments should set the environment variable to `""`. What about 

```
function load_api_key()
    ENV["API_FRED"] = read(joinpath(homedir(), ".freddatarc"), String)
    return nothing
end
```
? The function reads the `.freddatarc` file and overrides the local env variable, returns `nothing` such that the key is hidden from others and the key can still be accessed via `ENV["API_FRED"]`.
I'm not really happy with the name since it's behavior cannot be seen directly.

**Comment by proudindiv** [comment]
Sounds good to me

**Comment by markushhh** [comment]
I'd like to add a `write_api_key` method, but it feels bad to use/overwrite the runtime configuration file of `FredData.jl`.
Do you think there's a conflict of interest @proudindiv ? If so, would it be better to name the file `.fred_api_key`?

**Comment by proudindiv** [comment]
The two packages were and are delightfully independent.  I was able to load and use them both at the same time.

I think you are right to use the `.fred_api_key` file name.

**Comment by markushhh** [comment]
Ok. There's now `save_api_key` and `load_api_key` to save and load the `.fred_api_key` to the `homedir()`. Thx!
